<div class="content">
	<h2 class="page-header"><?php echo l('changelog'); ?></h2>

	<style>
	<?php foreach ($types as $type) { ?>
		.type_<?php echo $type->id; ?>:before {
			content: "<?php echo utf8_encode($type->bullet); ?>";
		}
	<?php } ?>
	</style>
	<?php foreach ($milestones as $milestone) { ?>
		<div class="panel panel-default">
			<div class="panel-heading"><strong><?php echo $milestone->name; ?></strong></div>
			<ul class="list-group">
			<?php foreach ($milestone->tickets->exec()->fetch_all() as $ticket) {
				if (!$types[$ticket->type_id]->changelog or !$ticket->status->changelog) {
					continue;
				}
			?>
				<?php echo HTML::link($ticket->summary, $ticket->href(), array('class' => 'list-group-item type_'.$ticket->type_id)); ?>
			<?php } ?>
			</ul>
		</div>
	<?php } ?>
</div>