<div class="content">
	<h2 class="page-header"><?php echo l('projects'); ?></h2>
	
		<?php foreach($projects as $project) { ?>
	<div class="panel panel-default">
		<div class="panel-heading">		
			<strong class="panel-title"><?php echo HTML::link($project->name, $project->slug); ?><?php echo ($project->codename ? " <em>\"{$project->codename}\"</em>" : ''); ?></strong>
		</div>
		<ul class="list-group">
			<?php echo HTML::link(l('roadmap'), "{$project->slug}/roadmap", array('class' => 'list-group-item')); ?>
			<?php echo HTML::link(l('tickets'), "{$project->slug}/tickets", array('class' => 'list-group-item')); ?>
			<?php echo HTML::link(l('timeline'), "{$project->slug}/timeline", array('class' => 'list-group-item')); ?>
			<?php echo HTML::link(l('changelog'), "{$project->slug}/changelog", array('class' => 'list-group-item')); ?>
			<?php if ($project->enable_wiki) { ?>
				<?php echo HTML::link(l('wiki'), "{$project->slug}/wiki", array('class' => 'list-group-item')); ?>
			<?php } ?>
			<?php FishHook::run('template:projects/index/project/nav', array($project)); ?>
			<li class="list-group-item list-group-item-info">				
				<div class="description">
					<?php echo format_text($project->info); ?>
				</div>
				<?php FishHook::run('template:projects/index/project', array($project)); ?>
			</li>
		</ul>
	</div>	
		<?php } ?>

</div>