<div class="content">
	<h2 class="page-header"><?php echo l('projects'); ?></h2>
	
		<?php foreach($projects as $project) { ?>
	<div class="panel panel-default">
		<div class="panel-heading">		
			<strong><?php echo HTML::link($project->name, $project->slug); ?><?php echo ($project->codename ? " <em>\"{$project->codename}\"</em>" : ''); ?></strong>
		</div>
		<div class="panel-body">		
			
				<nav>
					<ul>
						<li><?php echo HTML::link(l('roadmap'), "{$project->slug}/roadmap"); ?></li>
						<li><?php echo HTML::link(l('tickets'), "{$project->slug}/tickets"); ?></li>
						<li><?php echo HTML::link(l('timeline'), "{$project->slug}/timeline"); ?></li>
						<?php FishHook::run('template:projects/index/project/nav', array($project)); ?>
					</ul>
				</nav>
					
			<div class="description">
				<?php echo format_text($project->info); ?>
			</div>
			<?php FishHook::run('template:projects/index/project', array($project)); ?>
		</div>
	</div>	
		<?php } ?>

</div>