<script>
$(document).ready(function() {
    $('.progress .progress-bar').progressbar({display_text: 'center'});
});
</script>
<div class="content">
	<h2 class="page-header"><?php echo $milestone->name; ?></h2>
	<div>
		<?php echo subscription_link_for($milestone); ?>
	</div>
	<?php echo View::render('milestones/_progress'); ?>
	<div class="milestone_info">
		<?php echo format_text($milestone->info); ?>
	</div>
</div>
