<div class="roadmap content">
	<h2 id="page_title"><?php echo l('roadmap'); ?></h2>
</div>
	<ul class="nav nav-tabs" role="tablist">
		<li<?php echo iif(active_nav('/:slug/roadmap'), ' class="active"')?>><?php echo HTML::link(l('active'), $project->href('roadmap')); ?></li>
		<li<?php echo iif(active_nav('/:slug/roadmap/completed'), ' class="active"')?>><?php echo HTML::link(l('completed'), $project->href('roadmap/completed')); ?></li>
		<li<?php echo iif(active_nav('/:slug/roadmap/all'), ' class="active"')?>><?php echo HTML::link(l('all'), $project->href('roadmap/all')); ?></li>
	</ul>
	<div style="margin-top:20px">
		<?php foreach($milestones as $milestone) { ?>
			<div class="panel panel-default">
				<div class="panel-heading">
					<strong><?php echo HTML::link($milestone->name . ($milestone->codename != '' ? ' <em>"' . $milestone->codename . '"</em>' : ''), $milestone->href()); ?></strong>
				</div>
				<div class="list-group">
					<div class="list-group-item">
						<?php if ($milestone->due > 0 and $milestone->status == 1) { ?>
						<div class="due">
							<em><?php echo l('due_x', time_from_now_ago($milestone->due)); ?></em>
						</div>
						<?php } ?>
						<?php echo View::render('milestones/_progress', array('milestone' => $milestone)); ?>
					</div>
					<?php if($milestone->info !== '') { ?>
					<div class="list-group-item">
						<?php echo format_text($milestone->info); ?>
					</div>
					<?php } ?>
				</div>
			</div>
		<?php } ?>
	</div>
</div>
