<div id="ticket_task_bit_<?php echo $id?>" class="task">
<div class="form-group">
	<div class="col-sm-1">
		<?php echo Form::checkbox("tasks[{$id}][completed]", '1', array('checked' => $completed, 'data-task-id' => $id))?>
	</div>
	<div class="col-sm-9">
		<?php echo Form::text("tasks[{$id}][task]", array('value' => $task, 'data-task-id' => $id,'class' => 'form-control'))?>
	</div>
	<div class="col-sm-2">
		<button type="button" class="btn btn-danger delete_ticket_task" data-task-id="<?php echo $id?>"><?php echo l('delete')?></button>
	</div>
</div>
</div>
