
<script>
$(document).ready(function(){
  $('#myModal').modal('show')
});
</script>

<form class="form-horizontal" role="form" action="<?php echo Request::requestUri(); ?>" method="post">
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="manage_tasks" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="manage_tasks" id="edit_ticket"><?php echo l('manage_tasks'); ?></h4>
				</div>
				<div class="modal-body">
					<?php //echo show_errors($task->errors); ?>
					<div id="ticket_tasks_manager">
						<div class="tasks">
							<input type="hidden" id="task_count" name="task_count" value="0" class="form-control">
						</div>
						<button type="button" id="add_task" class="btn btn-success"><?php echo l('add_task')?></button>
					</div>
				</div>
				<div class="modal-footer">
			
					<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo l('close'); ?></button>
					
					<input type="submit" id="set_ticket_tasks" class="btn btn-primary" value="<?php echo l('save'); ?>" />
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
</form>
