<div class="content">
	<?php echo HTML::link(l('new_status'), '/admin/tickets/statuses/new', array('class' => 'btn btn-primary', 'data-overlay' => true)); ?>
</div>
<div>
	<table class="table table-hover">
		<thead>
			<tr>
				<th><?php echo l('name'); ?></th>
				<th><!--?php echo l('actions'); ?--></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($statuses as $status) { ?>
			<tr>
				<td><?php echo HTML::link($status->name, "/admin/tickets/statuses/{$status->id}/edit", array('data-overlay' => true)); ?></td>
				<td align="right">
					<?php echo HTML::link(l('edit'), "/admin/tickets/statuses/{$status->id}/edit", array('class' => 'label label-warning', 'data-overlay' => true)); ?>
					<?php echo HTML::link(l('delete'), "/admin/tickets/statuses/{$status->id}/delete", array('class' => 'label label-danger', 'data-confirm' => l('confirm.delete_x', $status->name))); ?>
				</td>
			</tr>
		<?php } ?>
		</tbody>
	</table>
</div>