<div class="panel panel-default">
	<div class="panel-heading">
		<strong><?php echo l('edit_group'); ?></strong>
	</div>
	
	<div class="panel-body">
		<form class="form-horizontal" role="form" action="<?php echo Request::requestUri(); ?>" method="post">
			<?php echo show_errors($group->errors); ?>
			<div class="tabular box">
				<?php echo View::render('admin/groups/_form'); ?>
			</div>
			<center><div class="btn-group">
				<input type="submit" class="btn btn-success" value="<?php echo l('save'); ?>" />
				<?php echo HTML::link(l('cancel'), '/admin/groups', array('class' => 'btn btn-danger')); ?>
			</div></center>
		</form>
	</div>
</div>