<div class="well well-lg">
	<?php echo HTML::link(l('new_role'), '/admin/roles/new', array('class' => 'btn btn-primary')); ?>
	<table class="table table-hover">
		<thead>
			<tr>
				<th><?php echo l('name'); ?></th>
				<th><?php echo l('assignable'); ?></th>
				<th><?php echo l('project'); ?></th>
				<th><!--?php echo l('actions'); ?--></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($roles as $role) { ?>
			<tr>
				<td><?php echo HTML::link($role->name, "/admin/roles/{$role->id}/edit"); ?></td>
				<td><?php echo $role->assignable ? '&#10003;' : '&times;' ?></td>
				<td><?php echo $role->project_id > 0 ? $role->project->name : l('all'); ?></td>
				<td align="right">
					<?php echo HTML::link(l('edit'), "/admin/roles/{$role->id}/edit", array('class' => 'label label-warning')); ?>
					<?php echo HTML::link(l('delete'), "/admin/roles/{$role->id}/delete", array('class' => 'label label-danger', 'data-confirm' => l('confirm.delete_x', $role->name))); ?>
				</td>
			</tr>
		<?php } ?>
		</tbody>
	</table>
</div>
