<div class="admin content">
	<h2><?php echo l('dashboard'); ?></h2>

	<div id="update">
	<?php if (settings('check_for_update')) { ?>
		<?php echo View::render('admin/dashboard/_update'); ?>
	<?php } else { ?>
		<strong><?php echo HTML::link(l('check_for_update'), '/admin/check_for_update'); ?></strong>
	<?php } ?>
	</div>
	
	<div class="row">
	
		<div class="col-md-7">
			
			<h3><?php echo l('tickets'); ?></h3>
			<div class="panel panel-default">
					
				<div class="panel-body">	
					<button class="btn btn-primary" href="#"><?php echo l('open'); ?> <span class="badge"><?php echo $tickets['open']; ?></span></button>
					
					<button class="btn btn-primary" href="#"><?php echo l('closed'); ?> <span class="badge"><?php echo $tickets['closed']; ?></span></button>

					<button class="btn btn-primary" href="#"><?php echo l('total'); ?> <span class="badge"><?php echo $tickets['open'] + $tickets['closed']; ?></span></button>
				</div>
					
			</div>
		
		</div> <!-- END Collum md 6 -->

		<div class="col-md-5">
			
			<h3><?php echo l('users'); ?></h3>
			<div class="box">
				<dl>
					<dt><?php echo l('total'); ?></dt>
					<dd><?php echo $users; ?></dd>

					<dt><?php echo l('newest'); ?></dt>
					<dd><?php echo HTML::link($latest_user->username, $latest_user->href()); ?></dd>
				</dl>
			</div>
		
		</div> <!-- END Collum md 6 -->
	
	</div>
	
</div>
