<tr>
	<td><?php echo l("permissions." . (isset($key) ? "{$key}." : '') . "{$action}"); ?></td>
	<?php foreach ($groups as $group) {
	$perm = $permissions[$group->id][$action];
	?>
	<td>
		<?php
			echo Form::select("perm[{$group->id}][{$perm->id}]",
				($group->id == 0 ? $options['defaults'] : $options['all']),
				array(
					'value' => ($group->id == 0 ? $perm->value : ($perm->type_id == 0 ? -1 : $perm->value)), 'class' => "form-control"
				)
			);
		?>
	</td>
	<?php } ?>
</tr>