<div class="content">
	<h2 id="page_title"><?php echo l('project_settings'); ?></h2>
</div>
<?php echo View::render('project_settings/_nav'); ?>
<div class="toolbar">
</div>
<form action="<?php echo Request::requestUri(); ?>" method="post">
	<table class="table table-hover">
		<thead>
			<tr>
				<th><?php echo l('action'); ?></th>
			<?php foreach ($groups as $group) { ?>
				<th><?php echo $group->name; ?></th>
			<?php } ?>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($actions as $key => $action) { ?>
			<?php if (is_array($action)) { ?>
			<tr class="permission_section">
				<td class="permissions_header" colspan="<?php echo count($groups) + 1; ?>"><?php echo l($key); ?></td>
			</tr>
			<?php foreach ($action as $act) {
				echo View::render('project_settings/permissions/_permission_row', array('key' => $key, 'action' => $act));
				}
			} else {
				echo View::render('project_settings/permissions/_permission_row', array('action' => $action));
			}
		} ?>
		</tbody>
	</table>
	<center>
		<input type="submit" class="btn btn-primary" value="<?php echo l('save'); ?>" />
	</center>
</form>
