<div class="content">
	<h2 class="page-header"><?php echo l('project_settings'); ?></h2>
</div>
<?php echo View::render('project_settings/_nav'); ?>
<div class="toolbar">
	<?php if (isset($errors)) { show_errors($errors); } ?>
	<form class="form-horizontal" role="form"  action="<?php echo Request::base($project->href("settings/members/new")); ?>" method="post">
		<div class="form-group">
			<label for="username" class="col-sm-2 control-label"><?php echo l('username'); ?></label>
			<div class="col-sm-10">
				<?php echo Form::text('username', array('data-autocomplete' => Request::base('/_ajax/autocomplete/username'), 'class' => 'form-control', 'id' => 'username')); ?>
			</div>		
		</div>
		<div class="form-group">
			<label for="role" class="col-sm-2 control-label"><?php echo l('role'); ?></label>
			<div class="col-sm-10">
				<?php echo Form::select('role', traq\models\ProjectRole::select_options(), array('class' => 'form-control','id' => 'role')); ?>
			</div>			
		</div>
		<div class="form-group">		
			<input type="submit" class="btn btn-success" value="<?php echo l('add'); ?>" />
		</div>
	</form>
</div>
<div>
	<form action="<?php echo Request::base($project->href("settings/members/save"));; ?>" method="post">
		<table class="table table-hover">
			<thead>
				<tr>
					<th class="fixed_name"><?php echo l('username'); ?></th>
					<th class="fixed_name"><?php echo l('name'); ?></th>
					<th class="role"><?php echo l('role'); ?></th>
					<!--<th class="actions"><?php //echo l('actions'); ?></th>-->
				</tr>
			</thead>
			<tbody>
			<?php foreach ($user_roles as $rel) { ?>
				<tr>
					<td><?php echo $rel->user->username; ?></td>
					<td><?php echo $rel->user->name; ?></td>
					<td><?php echo Form::select("role[{$rel->id}]", traq\models\ProjectRole::select_options(), array('value' => $rel->project_role_id, 'class' => "form-control", 'id' => "group")); ?></td>
					<td align="right"><?php echo HTML::link(l('delete'), $project->href("settings/members/{$rel->user_id}/delete"), array('class' => 'btn btn-xs btn-danger', 'data-confirm' => l('confirm.remove_x', $rel->user->username))); ?></td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
		<div class="actions">
			<input type="submit" class="btn btn-success" value="<?php echo l('save'); ?>" />
		</div>
	</form>
</div>
