<div class="content">
	<h2 id="page_title"><?php echo l('project_settings'); ?></h2>
</div>
<?php echo View::render('project_settings/_nav'); ?>
<div class="content">
	<?php echo HTML::link(l('new_milestone'), "{$project->slug}/settings/milestones/new", array('class' => 'btn btn-primary', 'data-overlay' => true)); ?>
</div>
<div>
	<table class="table table-hover">
		<thead>
			<tr>
				<th><?php echo l('name'); ?></th>
				<th><?php echo l('codename'); ?></th>
				<th><?php echo l('due'); ?></th>
				<th><?php echo l('status'); ?></th>
				<th><!--?php echo l('actions'); ?--></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($milestones->exec()->fetch_all() as $milestone) { ?>
			<tr>
				<td><?php echo HTML::link($milestone->name, "{$project->slug}/settings/milestones/{$milestone->id}/edit", array('data-overlay' => true)); ?></td>
				<td><?php echo $milestone->codename; ?></td>
				<td><?php if($milestone->due and $milestone->status == 1) {
						echo time_from_now_ago($milestone->due);
					} elseif ($milestone->due and $milestone->status == 2) {
						echo l('completed');
					} ?></td>
				<td><?php echo $milestone->status == 0 ? l('cancelled') : ($milestone->status == 1 ? l('active') : l('completed')); ?></td>
				<td align="right">
					<?php echo HTML::link(l('edit'), "{$project->slug}/settings/milestones/{$milestone->id}/edit", array('class' => 'label label-warning', 'data-overlay' => true)); ?>
					<?php echo HTML::link(l('delete'), "{$project->slug}/settings/milestones/{$milestone->id}/delete", array('class' => 'label label-danger', 'data-confirm' => l('confirm.delete_x', $milestone->name))); ?>
				</td>
			</tr>
		<?php } ?>
		</tbody>
	</table>
</div>
