<div class="form-group">
	<label for="title" class="col-sm-2 control-label"><?php echo l('page_title'); ?></label>
	<div class="col-sm-10">
		<?php echo Form::text('title', array('value' => $page->title, 'class' => 'form-control', 'id' => 'title', 'required' => true)); ?>
	</div>
</div>
<div class="form-group">
	<label for="slug" class="col-sm-2 control-label"><?php echo l('slug'); ?></label>
	<div class="col-sm-10">
		<?php echo Form::text('slug', array('value' => $page->slug, 'class' => 'form-control', 'id' => 'slug', 'required' => true)); ?>
		<abbr title="<?php echo l('help.slug'); ?>">?</abbr>
	</div>
</div>
<div class="form-group">
	<label for="page_content" class="col-sm-2 control-label"><?php echo l('page_content'); ?></label>
	<div class="col-sm-10">
		<?php echo Form::textarea('body', array('value' => htmlspecialchars($page->revision->content), 'class' => 'editor form-control', 'rows' => '6')); ?>
	</div>
</div>