<?php echo View::render('wiki/_nav'); ?>
<div class="content">
	<div id="head">
		<h2 class="page-header"><?php echo l('edit_page'); ?></h2>
	</div>
	<form class="form-horizontal" role="form" action="<?php echo Request::requestUri(); ?>" method="post">
		<?php echo show_errors($page->errors); ?>
		<div class="tabular box">
			<?php echo View::render('wiki/_form', array('page' => $page)); ?>
		</div>
		<div class="actions">
			<input type="submit" class="btn btn-success" value="<?php echo l('save'); ?>" />
		</div>
	</form>
</div>
