<div class="content">
<h2 class="page-header"><?php echo l('roles'); ?></h2>

	<?php echo HTML::link(l('new_role'), '/admin/roles/new', array('class' => 'btn btn-primary', 'data-overlay' => true)); ?>
	<table class="table table-hover">
		<thead>
			<tr>
				<th><?php echo l('name'); ?></th>
				<th><?php echo l('project'); ?></th>
				<th><?php echo l('assignable'); ?></th>				
				<th><!--?php echo l('actions'); ?--></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($roles as $role) { ?>
			<tr>
				<td><?php echo HTML::link($role->name, "/admin/roles/{$role->id}/edit", array('data-overlay' => true)); ?></td>
				<td><?php echo $role->project_id > 0 ? $role->project->name : l('all'); ?></td>
				<td><?php echo $role->assignable ? '&#10003;' : '&times;' ?></td>				
				<td align="right">
					<?php echo HTML::link(l('edit'), "/admin/roles/{$role->id}/edit", array('class' => 'btn btn-xs btn-warning', 'data-overlay' => true)); ?>
					<?php echo HTML::link(l('delete'), "/admin/roles/{$role->id}/delete", array('class' => 'btn btn-xs btn-danger', 'data-confirm' => l('confirm.delete_x', $role->name))); ?>
				</td>
			</tr>
		<?php } ?>
		</tbody>
	</table>
</div>
