<div class="well well-lg">
	<?php echo HTML::link(l('new_type'), '/admin/tickets/types/new', array('class' => 'btn btn-primary', 'data-overlay' => true)); ?>
	<table class="table table-hover">
		<thead>
			<tr>
				<th><?php echo l('name'); ?></th>
				<th><!--?php echo l('actions'); ?--></th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($types as $type) { ?>
			<tr>
				<td><?php echo HTML::link($type->name, "/admin/tickets/types/{$type->id}/edit", array('data-overlay' => true)); ?></td>
				<td align="right">
					<?php echo HTML::link(l('edit'), "/admin/tickets/types/{$type->id}/edit", array('class' => 'label label-warning', 'data-overlay' => true)); ?>
					<?php echo HTML::link(l('delete'), "/admin/tickets/types/{$type->id}/delete", array('class' => 'label label-danger', 'data-confirm' => l('confirm.delete_x', $type->name))); ?>
				</td>
			</tr>
		<?php } ?>
		</tbody>
	</table>
</div>