<div class="panel panel-default">
	<div class="panel-heading">
		<strong><?php echo l('login'); ?></strong>
	</div>
	<div class="panel-body">
	<?php if (!isset($validation_required)) { ?>
		<?php if (isset($error) and $error) { ?>
		<div class="error">
			<?php echo l('errors.invalid_username_or_password'); ?>
		</div>
		<?php } ?>
		<?php if (isset($validated) and $validated) { ?>
		<div class="success">
			<?php echo l('account_validated')?>
		</div>
		<?php } ?>
		<form class="form-horizontal" role="form" action="<?php echo Request::base('login'); ?>" method="post">
			<?php if (!empty($_SERVER['HTTP_REFERER']) or isset(Request::$post['redirect'])) { ?>
			<input type="hidden" name="redirect" value="<?php echo (isset(Request::$post['redirect'])) ? Request::$post['redirect'] : $_SERVER['HTTP_REFERER']; ?>" />
			<?php } ?>
			<div class="form-group">
				<label for="username" class="col-sm-2 control-label"><?php echo l('username'); ?></label>
				<div class="col-sm-10">	
					<?php echo Form::text('username', array('class' => "form-control", 'id' => "username")); ?>
				</div>	
			</div>
			<div class="form-group">
				<label for="password" class="col-sm-2 control-label"><?php echo l('password'); ?></label>
				<div class="col-sm-10">	
					<?php echo Form::password('password', array('class' => "form-control", 'id' => "password")); ?>
				</div>	
			</div>
			<center><div class="btn-group">
				<input type="submit" class="btn btn-primary" value="<?php echo l('login'); ?>" />
				<?php echo HTML::link(l('forgot_password'), '/login/resetpassword', array('class' => 'btn btn-warning')); ?>
			</div></center>
		</form>
<?php } else { ?>
		<div class="error">
			<?php echo l('errors.email_validation_required')?>
		</div>
<?php } ?>
	</div>
</div>
