<div class="content">
	<h2 class="page-header"><?php echo l('dashboard'); ?></h2>

	<div id="update">
	<?php if (settings('check_for_update')) { ?>
		<?php echo View::render('admin/dashboard/_update'); ?>
	<?php } else { ?>
		<strong><?php echo HTML::link(l('check_for_update'), '/admin/check_for_update'); ?></strong>
	<?php } ?>
	</div>
	
	<div class="row">
	
		<div class="col-md-5">
			
			<div class="panel panel-default">
				
				<div class="panel-heading">
					<strong class="panel-title"><?php echo l('tickets'); ?></strong>
				</div>
				
				<ul class="list-group">
					<li class="list-group-item"><span class="badge"><?php echo $tickets['open']; ?></span><?php echo l('open'); ?></li>
					<li class="list-group-item"><span class="badge"><?php echo $tickets['closed']; ?></span><?php echo l('closed'); ?></li>
					<li class="list-group-item"><span class="badge"><?php echo $tickets['open'] + $tickets['closed']; ?></span><?php echo l('total'); ?></li>
				</ul>
					
			</div>
		
		</div> <!-- END Collum md 6 -->

		<div class="col-md-2"></div> <!-- Fixing Position -->
		
		<div class="col-md-5">
			
			<div class="panel panel-default">
				
				<div class="panel-heading">
					<strong class="panel-title"><?php echo l('users'); ?></strong>
				</div>
			
				<ul class="list-group">
					<li class="list-group-item"><span class="badge"><?php echo $users; ?></span><?php echo l('total'); ?></li>
					<li class="list-group-item"><?php echo l('newest').":"; ?>
					<span class="pull-right"><?php echo HTML::link($latest_user->username, $latest_user->href()); ?>
					</li>
				</div>
			
			</div>	
			
		</div> <!-- END Collum md 6 -->	
		
	</div>
	<div class="row">		
		<div id="traq_news" class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<strong class="panel-title"><?php echo l('traq_news'); ?></strong>
				</div>	
				<div classs="panel-body">
					<ul></ul>
				</div>
			</div>	
		</div>
	</div>	
	<div class="alert alert-danger alert-dismissible fade in">
		<?php echo l('admin.news.secure_connection'); ?>
	</div>	
</div>
