<script>
$(document).ready(function(){
  $('#myModal').modal('show')
});
</script>
<form class="form-horizontal" role="form" action="<?php echo Request::requestUri(); ?>" method="post">
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="edit_field" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title" id="edit_field"><?php echo l('edit_field'); ?></h4>
				</div>
				<div class="modal-body">
					<?php echo show_errors($field->errors); ?>
					<div class="tabular box">
					<?php echo View::render('project_settings/custom_fields/_form'); ?>
					</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo l('close'); ?></button>
					<input type="submit" class="btn btn-success" value="<?php echo l('save'); ?>" />
				</div>
			</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
</form>
