<div class="content">
	<h2 class="page-header"><?php echo l('project_settings'); ?></h2>
</div>
<?php echo View::render('project_settings/_nav'); ?>
<div class="toolbar">
	<?php echo HTML::link(l('new_field'), "{$project->slug}/settings/custom_fields/new", array('class' => 'btn btn-primary', 'data-overlay' => true)); ?>
</div>
<div>
	<table class="table table-hover">
		<thead>
			<tr>
				<th class="name"><?php echo l('name'); ?></th>
				<th class="type"><?php echo l('type'); ?></th>
				<!--<th class="actions"><?php //echo l('actions'); ?></th>-->
			</tr>
		</thead>
		<tbody>
		<?php foreach ($custom_fields as $field) { ?>
			<tr>
				<td><?php echo HTML::link($field->name, "{$project->slug}/settings/custom_fields/{$field->id}/edit", array('data-overlay' => true)); ?></td>
				<td><?php echo l($field->type); ?></td>
				<td align="right">
					<?php echo HTML::link(l('edit'), "{$project->slug}/settings/custom_fields/{$field->id}/edit", array('class' => 'btn btn-xs btn-warning', 'data-overlay' => true)); ?>
					<?php echo HTML::link(l('delete'), "{$project->slug}/settings/custom_fields/{$field->id}/delete", array('class' => 'btn btn-xs btn-danger', 'data-confirm' => l('confirm.delete_x', $field->name))); ?>
				</td>
			</tr>
		<?php } ?>
		</tbody>
	</table>
</div>
