<?php $config = parse_ini_file( APPPATH . '/views/' . settings('theme') . '/config/config.ini' ); ?>
<title><?php echo implode(' - ', array_reverse($traq->title)); ?></title>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="<?php echo Request::base('vendor/traq/views/' . settings('theme') . '/css/bootstrap.min.css'); ?>" media="screen">
		<?php echo HTML::css_link('//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css'); ?>
		<link rel="stylesheet" href="<?php echo Request::base('vendor/traq/views/' . settings('theme') . '/css/style.css'); ?>" media="screen">
		<link rel="stylesheet" href="<?php echo Request::base('vendor/traq/views/' . settings('theme') . '/css/theme-'.$config['theme'].'.css'); ?>" media="screen">
		<link rel="stylesheet" href="<?php echo Request::base('vendor/traq/views/' . settings('theme') . '/css/animated-progressbar.css'); ?>" media="screen">

		<!--[if lt IE 8]>
		<?php //echo HTML::css_link(Request::base() . 'css.php?css=ie'); ?>
		<![endif]-->
		<?php echo HTML::js_inc('//code.jquery.com/jquery-1.11.0.min.js'); ?>
		<?php FishHook::run('template:layouts/global/head'); ?>
<?php foreach ($app->feeds as $feed) { ?><link type="application/atom+xml" rel ="alternate" href="<?php echo $feed[0]; ?>">
<?php } ?>
