<?php $config = parse_ini_file( APPPATH . '/views/' . settings('theme') . '/config/config.ini' ); ?>
	<li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user fa-lg"></i> <?php if (LOGGEDIN) { echo ($current_user->name); } else { echo ('Not logged in'); } ?> <span class="caret"></span></a>
		<ul class="dropdown-menu" role="menu">
			<?php FishHook::run('template:layouts/_meta_nav/user_nav'); ?>
			<?php if (LOGGEDIN) { ?>
				<li<?php echo iif(active_nav(current_user()->href()), ' class="active"')?>><?php echo HTML::link(l('profile'), current_user()->href()) ?></li>
				<li<?php echo iif(active_nav('/usercp'), ' class="active"')?>><?php echo HTML::link(l('usercp'), '/usercp'); ?></li>
				<?php if ($current_user->group->is_admin) { ?>
				<li<?php echo iif(active_nav('/admin(.*)'), ' class="active"')?>><?php echo HTML::link(l('admincp'), '/admin'); ?></li>
				<li class="divider"></li>
				<li<?php if ($config['navbar'] == "default") { echo ' class="active"'; } ?>><a>Light Navbar</a></li>
				<li<?php if ($config['navbar'] == "inverse") { echo ' class="active"'; } ?>><a>Dark Navbar</a></li>
				<?php } ?>
				<li class="divider"></li>
				<li><?php echo HTML::link(l('logout'), '/logout'); ?></li>
			<?php } else { ?>
				<li<?php echo iif(active_nav('/login'), ' class="active"')?>><?php echo HTML::link(l('login'), '/login'); ?></li>
				<?php if (settings('allow_registration')) { ?>
				<li<?php echo iif(active_nav('/register'), ' class="active"')?>><?php echo HTML::link(l('register'), '/register'); ?></li>
				<?php } ?>
			<?php } ?>
		</ul>
	</li>