<?php if ($pagination->paginate) { ?>
<div class="content">
	<ul class="pagination">
	<?php if ($pagination->prev_page_url) { ?>
		<li><a href="<?php echo $pagination->prev_page_url; ?>" class="button_previous prev_link"><?php echo l('previous'); ?></a></li>
	<?php } ?>
	<?php if ($pagination->next_page_url) { ?>
		<li><a href="<?php echo $pagination->next_page_url; ?>" class="button_next next_link"><?php echo l('next'); ?></a></li>
	<?php } ?>
		<div class="clearfix"></div>
	</ul>
</div>
<?php } ?>