<?php $config = parse_ini_file( APPPATH . '/views/' . settings('theme') . '/config/config.ini' ); ?>
<?php 
if ($current_user->group->is_admin) {
	if (isset($_GET['theme']) && $_GET['theme'] == "light") {
		
		$config[ 'theme' ] = "default"; //Lets set the theme to default
		$f = fopen( APPPATH . '/views/' . settings('theme') . '/config/config.ini', "w" );
		foreach ( $config as $name => $value )
		{
			fwrite( $f, "$name = \"$value\"\n" );
		}
		
		fclose( $f );
		
		header("Location: ".Request::base()); //Everything done? lets go back to the main site
		
	}
	if (isset($_GET['theme']) && $_GET['theme'] == "dark") {
		
		$config[ 'theme' ] = "inverse"; //Lets set the theme to inverse
		$f = fopen( APPPATH . '/views/' . settings('theme') . '/config/config.ini', "w" );
		foreach ( $config as $name => $value )
		{
			fwrite( $f, "$name = \"$value\"\n" );
		}
		
		fclose( $f );
		
		header("Location: ".Request::base()); //Everything done? lets go back to the main site
		
	}
}
?>
<!DOCTYPE html>
<html>
	<head>
		<?php echo View::render('layouts/_head'); ?>
		<?php FishHook::run('template:layouts/admin/head'); ?>
		<script>
			$(document).ready(function() {
				$('.container').fadeIn();
			});
		</script>
	</head>
	<body>
		<div id="overlay"></div>
		<div id="popover" class="popover"></div>
		<nav class="navbar navbar-<?php echo $config['theme']; ?> navbar-static-top" role="navigation">
				
			<div class="container-fluid">
		
				<div class="navbar-header">

					<button type="button" style="z-index:1;" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						
					</button>
						
					<ul class="nav dropdown">
						<a class="navbar-brand" data-toggle="dropdown" href="#">AdminCP <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<?php if (settings('site_name') !== '') { ?>
								<li><a href="<?php echo settings('site_url'); ?>"><?php echo settings('site_name'); ?></a></li>
							<?php } ?>
							<?php if (Request::seg(0)) { ?>
								<li><?php echo HTML::link(settings('title'), '/'); ?></li>
							<?php } ?>
						</ul>
					</ul>
					<?php //echo View::render('layouts/_project_switcher'); ?>
					
				</div>
			
				<div class="collapse navbar-collapse">
				
					<ul class="nav navbar-nav">
					
						<li<?php echo iif(active_nav('/admin'), ' class="active"')?>><?php echo HTML::link(l('dashboard'), "/admin"); ?></li>
						<li<?php echo iif(active_nav('/admin/settings(.*)'), ' class="active"')?>><?php echo HTML::link(l('settings'), "/admin/settings"); ?></li>
						<li<?php echo iif(active_nav('/admin/projects(.*)'), ' class="active"')?>><?php echo HTML::link(l('projects'), "/admin/projects"); ?></li>
						<li<?php echo iif(active_nav('/admin/roles(.*)'), ' class="active"')?>><?php echo HTML::link(l('roles'), "/admin/roles"); ?></li>
						<li<?php echo iif(active_nav('/admin/users(.*)'), ' class="active"')?>><?php echo HTML::link(l('users'), "/admin/users"); ?></li>
						<li<?php echo iif(active_nav('/admin/groups(.*)'), ' class="active"')?>><?php echo HTML::link(l('groups'), "/admin/groups"); ?></li>
						<li<?php echo iif(active_nav('/admin/plugins(.*)'), ' class="active"')?>><?php echo HTML::link(l('plugins'), "/admin/plugins"); ?></li>
						<li<?php echo iif(active_nav('/admin/tickets/types(.*)'), ' class="active"')?>><?php echo HTML::link(l('types'), "/admin/tickets/types"); ?></li>
						<li<?php echo iif(active_nav('/admin/tickets/statuses(.*)'), ' class="active"')?>><?php echo HTML::link(l('statuses'), "/admin/tickets/statuses"); ?></li>
						<li<?php echo iif(active_nav('/admin/priorities(.*)'), ' class="active"')?>><?php echo HTML::link(l('priorities'), "/admin/priorities"); ?></li>
						<li<?php echo iif(active_nav('/admin/severities(.*)'), ' class="active"')?>><?php echo HTML::link(l('severities'), "/admin/severities"); ?></li>
						<?php FishHook::run('template:layouts/admin/main_nav'); ?>
					
					</ul>
					
					<ul class="nav navbar-nav navbar-right">
						
						<?php echo View::render('layouts/_meta_nav'); ?>
						
					</ul>
					
				</div> <!-- END Navbar Collapse -->
			
			</div> <!-- END Navbar Container -->
			
		</nav>
		<div class="container" style="display:none;">
		<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-10">
<?php echo $content; ?>
		</div>
		<div class="col-md-1"></div>
		</div>
		</div>
		
		<footer>
				
				<div class="container-fluid">
						
							<?php echo l('copyright', TRAQ_VER, date("Y")); ?>
							<p class="footer-right">Bootstrap Theme by <a href="http://github.com/paulhobbel">Paul Hobbel</a></p>
				
				</div>
				
		</footer>
		<!-- Start all javascript for a faster page load -->
		<?php echo HTML::js_inc('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js'); ?>
		<script src="<?php echo Request::base('vendor/traq/views/' . settings('theme') . '/js/animated-progressbar.js'); ?>" type="text/javascript"></script>
		<?php //echo HTML::js_inc(Request::base() . 'js.php?js=all'); ?>
		<?php echo HTML::js_inc(Request::base() . 'js.php?js=jquery.cookie'); ?>
		<script src="<?php echo Request::base('vendor/traq/views/' . settings('theme') . '/js/likeaboss.js'); ?>" type="text/javascript"></script>
		<?php echo HTML::js_inc(Request::base() . 'js.php?js=mass_actions'); ?>
		<?php echo HTML::js_inc(Request::base() . 'js.php?js=popover'); ?>
		<?php echo HTML::js_inc(Request::base() . 'js.php?js=ticket_tasks'); ?>
		<script src="<?php echo Request::base('vendor/traq/views/' . settings('theme') . '/js/traq.js'); ?>" type="text/javascript"></script>
		<?php echo HTML::js_inc(Request::base() . 'js.php?js=traq_news'); ?>
		<?php echo HTML::js_inc(Request::base('_js')); ?>
		<script>
			// ADD FADEIN ANIMATION TO DROPDOWN //
			$('.dropdown').on('show.bs.dropdown', function(e){
				$(this).find('.dropdown-menu').fadeIn();
			});

			// ADD FADEOUT ANIMATION TO DROPDOWN //
			$('.dropdown').on('hide.bs.dropdown', function(e){
				$(this).find('.dropdown-menu').hide(); //Had to change this because slideDown and fadeOut was kinda bugy on phone's
			});
		</script>
		<script>
			$( document ).ready(function() {
				$('[data-toggle="tooltip"]').tooltip({'placement': 'top'});
			});
		</script>
		<!-- End of javascript start -->
		<!-- <?php echo round((microtime(true) - START_TIME), 2); ?>s, <?php echo round((memory_get_peak_usage() - START_MEM) / pow(1024, 2), 3); ?>mb -->
	</body>

</html>
