<form action="<?php echo Request::requestUri(); ?>" method="post">
	<div class="panel-group" id="accordion">
		<div class="panel panel-default">
			<div class="panel-heading">
				<strong class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse2"><?php echo l('columns'); ?></a></strong>
			</div>
			<div id="collapse2" class="panel-collapse collapse">
				<div class="panel-body">	
					<?php foreach (ticketlist_allowed_columns() as $column) { ?>
						<?php echo Form::checkbox("columns[{$column}]", $column, array('checked' => in_array($column, $columns))); ?>
						<?php echo Form::label(ticketlist_header($column), "columns[{$column}]"); ?>
					<?php } ?>
					<?php foreach($custom_fields as $column) { ?>
						<?php echo Form::checkbox("columns[{$column->id}]", $column->id, array('checked' => in_array($column->name, $columns)))?>
						<?php echo Form::label($column->name, "columns[{$column->id}]")?>
					<?php } ?>
				</div>
				<div class="panel-footer">
					<div class="actions">
						<?php echo Form::submit(l('update'), 'update_columns', array('class' => 'btn btn-primary')); ?>
					</div>												
				</div>			
					
			</div>
		</div>
	</div>				
</form>
