<div class="panel panel-default" id="ticket_filters">
	<div class="panel-heading">
		<strong class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse1"><?php echo l('filters'); ?></a></strong>
	</div>
	<div id="collapse1" class="panel-collapse collapse in">
		<form action="<?php echo Request::base($project->href('tickets/update_filters')); ?>" method="post">
			<div class="table-responsive">
				<table style="margin-bottom:0;" class="table table-hover">
					<tbody>
					<?php foreach ($filters as $filter => $info) { ?>
						<?php if (in_array($filter, array('milestone', 'status', 'version', 'type', 'component', 'priority', 'severity', 'search'))) { ?>
						<tr id="filter-<?php echo $filter; ?>">
							<td><?php echo l($filter); ?></td>
							<?php if ($filter == 'search') { ?>
							<td class="condition">is</td>
							<td class="value">
								<?php echo Form::text("filters[{$filter}][values][]", array('value' => implode(',', $info['values']), 'id' => false, 'class' => 'form-control')); ?>
							</td>
							<?php } else { ?>
							<td class="condition">
								<?php
									echo Form::select("filters[{$filter}][prefix]",
										array(
											array('label' => l('is'), 'value' => ''),
											array('label' => l('is_not'), 'value' => '!')
										),
										array('value' => $info['prefix'], 'id' => false, 'class' => 'form-control')
									);
								?>
							</td>
							<td class="value">
								<?php echo Form::multiselect("filters[{$filter}][values][]", ticket_filter_options_for($filter, $project->id), $info['values'], array('class' => 'form-control')); ?>
							</td>
							<?php } ?>
							<td class="ticket_filter_action">
								<button type="button" class="button_delete btn btn-danger" name="remove_filter[<?php echo $filter; ?>:<?php echo $k; ?>]" data-filter="<?php echo $filter; ?>">-</button>
							</td>
						</tr>
						<?php } else { ?>
							<?php foreach ($info['values'] as $k => $value) { ?>
							<tr id="filter-<?php echo $filter; ?>-<?php echo $k; ?>">
								<td>
									<?php if (isset($info['label'])) { ?>
										<?php echo $info['label']; ?>
									<?php } else { ?>
										<?php echo $k == 0 ? l($filter) :''; ?>
									<?php } ?>
								</td>
								<td class="condition">
								<?php
									if ($k == 0) {
										if (in_array($filter, array('summary', 'description'))) {
											echo Form::select("filters[{$filter}][prefix]",
												array(
													array('label' => l('contains'), 'value' => ''),
													array('label' => l('does_not_contain'), 'value' => '!')
												),
												array('value' => $info['prefix'], 'id' => false, 'class' => 'form-control')
											);
										} else {
											echo Form::select("filters[{$filter}][prefix]",
												array(
													array('label' => l('is'), 'value' => ''),
													array('label' => l('is_not'), 'value' => '!')
												),
												array('value' => $info['prefix'], 'id' => false, 'class' => 'form-control')
											);
										}
									} else {
										echo l('or');
									}
								?>
								</td>
								<td class="value">
								<?php
									if (in_array($filter, array_merge(array('summary', 'description'), array_keys(ticket_filters_for($project))))) {
										echo Form::text("filters[{$filter}][values][]", array('value' => $value, 'id' => false, 'class' => 'form-control'));
									} elseif (in_array($filter, array('owner', 'assigned_to'))) {
										echo Form::text("filters[{$filter}][values][]", array('value' => $value, 'data-autocomplete' => Request::base('/_ajax/autocomplete/username'), 'id' => false, 'class' => 'form-control'));
									}
								?>
								</td>
								<td class="ticket_filter_action">
									<button type="button" class="button_delete btn btn-danger" name="remove_filter[<?php echo $filter; ?>:<?php echo $k; ?>]" data-filter="<?php echo $filter; ?>-<?php echo $k; ?>">-</button>
								</td>
							</tr>
							<?php } ?>
						<?php } ?>
					<?php } ?>
					</tbody>
				</table>
			</div>
			<div class="panel-footer">	
				<?php echo Form::submit(l('update'), 'update', array('class' => 'btn btn-success')); ?>
				<div class="pull-right" style="margin-left:5px;">
					<button type="submit" class="btn btn-success" name="add_filter">+</button>
				</div>
				<div class="pull-right">						
					<?php echo Form::select('new_filter', ticket_filters_select_options($project),array('class' => 'form-control')); ?>
				</div>
			</div>
		</form>
	</div>
</div>