<?php if ($current_user->permission($project->id, 'update_tickets') or $current_user->permission($project->id, 'comment_on_tickets')) { ?>
<div class="content">
	<h3 class="section_title"><?php echo l('update_ticket'); ?></h3>
	<?php echo show_errors($ticket->errors); ?>
	<form class="form-horizontal" role="form" action="<?php echo Request::base($ticket->href('update')); ?>" method="post" id="update_tickets" enctype="multipart/form-data">
		<div class="tabular box">
			<?php if ($current_user->permission($project->id, 'comment_on_tickets')) { ?>
			<div class="form-group">
				<label for="comment" class="col-sm-2 control-label"><?php echo l('comment'); ?></label>
				<div class="col-sm-10">
					<?php echo Form::textarea('comment', array('class' => 'form-control editor')); ?>
				</div>
			</div>
			<?php } ?>
			<?php if ($current_user->permission($project->id, 'update_tickets')) { ?>
			<div class="properties group">
				<?php if (current_user()->permission($project->id, 'ticket_properties_change_type')) { ?>
				<div class="form-group">
					<label for="type" class="col-sm-2 control-label"><?php echo l('type'); ?></label>
					<div class="col-sm-10">
						<?php echo Form::select('type', traq\models\Type::select_options(), array('value' => $ticket->type_id, 'class' => 'form-control', 'id' => 'type')); ?>
					</div>				
				</div>
				<?php } ?>
				<?php if (current_user()->permission($project->id, 'ticket_properties_change_assigned_to')) { ?>
				<div class="form-group">
					<label for="assigned_to" class="col-sm-2 control-label"><?php echo l('assigned_to'); ?></label>
					<div class="col-sm-10">
						<?php echo Form::select('assigned_to', array_merge(array(array('value' => 0, 'label' => l('none'))), $project->assignable_member_select_options()), array('value' => $ticket->assigned_to_id, 'class' => 'form-control', 'id' => 'assigned_to')); ?>
					</div>	
					
				</div>
				<?php } ?>
				<?php if (current_user()->permission($project->id, 'ticket_properties_change_milestone')) { ?>
				<div class="form-group">
					<label for="milestone" class="col-sm-2 control-label"><?php echo l('milestone'); ?></label>
					<div class="col-sm-10">					
					<?php echo Form::select(
						'milestone',
						($ticket->milestone and $ticket->milestone->status != 1) ? array_merge($ticket->milestone->select_option(), $project->milestone_select_options('open')) : $project->milestone_select_options('open'),
						array('value' => $ticket->milestone_id, 'class' => 'form-control')
					); ?>
					<abbr title="<?php echo l('help.milestone'); ?>" class="hint">?</abbr>
					</div>
				</div>
				<?php } ?>
				<?php if (current_user()->permission($project->id, 'ticket_properties_change_version')) { ?>
				<div class="form-group">
					<label for="version" class="col-sm-2 control-label"><?php echo l('version'); ?></label>
					<div class="col-sm-10">		
					<?php echo Form::select('version', array_merge(array(array('value' => 0, 'label' => l('none'))), $project->milestone_select_options('all', 'DESC')), array('value' => $ticket->version_id, 'class' => 'form-control')); ?>
					<abbr title="<?php echo l('help.version'); ?>" class="hint">?</abbr>
					</div>
				</div>
				<?php } ?>
				<?php if (current_user()->permission($project->id, 'ticket_properties_change_component')) { ?>
				<div class="form-group">
					<label for="component" class="col-sm-2 control-label"><?php echo l('component'); ?></label>
					<div class="col-sm-10">	
					<?php echo Form::select('component', array_merge(array(array('value' => 0, 'label' => l('none'))), traq\models\Component::select_options($project->id)), array('value' => $ticket->component_id, 'class' => 'form-control')); ?>
					<abbr title="<?php echo l('help.component'); ?>" class="hint">?</abbr>
				</div>
				<?php } ?>
				<?php if (current_user()->permission($project->id, 'ticket_properties_change_severity')) { ?>
				<div class="form-group">
					<label for="severity" class="col-sm-2 control-label"><?php echo l('severity'); ?></label>
					<div class="col-sm-10">	
					<?php echo Form::select('severity', traq\models\Severity::select_options(), array('value' => $ticket->severity_id, 'class' => 'form-control')); ?>
					<abbr title="<?php echo l('help.severity'); ?>" class="hint">?</abbr>
					</div>
				</div>
				<?php } ?>
				<?php if (current_user()->permission($project->id, 'ticket_properties_change_priority')) { ?>
				<div class="form-group">
					<label for="priority" class="col-sm-2 control-label"><?php echo l('priority'); ?></label>
					<div class="col-sm-10">	
					<?php echo Form::select('priority', traq\models\Priority::select_options(), array('value' => $ticket->priority_id, 'class' => 'form-control')); ?>
					</div>
				</div>
				<?php } ?>
				<?php if (current_user()->permission($project->id, 'ticket_properties_change_status')) { ?>
				<div class="form-group">
					<label for="status" class="col-sm-2 control-label"><?php echo l('status'); ?></label>
					<div class="col-sm-10">	
					<?php echo Form::select('status', traq\models\Status::select_options(), array('value' => $ticket->status_id, 'class' => 'form-control')); ?>
					</div>
				</div>
				<?php } ?>
				<?php if (current_user()->permission($project->id, 'ticket_properties_change_summary')) { ?>
				<div class="form-group">
					<label for="summary" class="col-sm-2 control-label"><?php echo l('summary'); ?></label>
					<div class="col-sm-10">	
					<?php echo Form::text('summary', array('value' => htmlspecialchars($ticket->summary), 'class' => 'form-control')); ?>
					</div>
				</div>
				<?php } ?>
				<?php if (current_user()->permission($project->id, 'ticket_properties_change_tasks')) { ?>
				<div class="form-group">
					<label for="tasks" class="col-sm-2 control-label"><?php echo l('tasks'); ?></label>
					<div class="col-sm-10">						
					<button type="button" class="btn btn-primary" id="manage_ticket_tasks" data-url="<?php echo Request::base($project->href("tickets/{$ticket->ticket_id}/tasks/manage"))?>"><?php echo l('manage')?></button>
					<div id="ticket_tasks_data">
						<input type="hidden" name="task_count" value="<?php echo count($ticket->tasks)?>">
						<input type="hidden" name="tasks" value="<?php echo htmlentities(json_encode($ticket->tasks))?>">
					</div>
					</div>
				</div>
				<?php } ?>
				<?php if ($current_user->permission($project->id, 'add_attachments')) { ?>
				<div class="form-group">
					<label for="attachment" class="col-sm-2 control-label"><?php echo l('attachment'); ?></label>
					<div class="col-sm-10">							
						<input type="file" id="attachment" name="attachment" />
					</div>
				</div>
				<?php } ?>
				<?php if ($current_user->permission($project->id, 'ticket_properties_change_related_tickets')) { ?>
				<div class="form-group">
					<label for="related_tickets" class="col-sm-2 control-label"><?php echo l('related_tickets'); ?></label>
					<div class="col-sm-10">	
					<?php echo Form::text('related_tickets', array('value' => implode(', ', $ticket->related_ticket_tids(false)), 'class' => 'form-control')); ?>
					</div>
				</div>
				<?php } ?>
				<?php echo View::render('tickets/_custom_fields_form'); ?>
			</div>
			<?php } ?>
			<div class="clear"></div>
		</div>
		<div class="actions">
			
			<input type="submit" class="btn btn-success" value="<?php echo l('submit'); ?>" />
			<input type="button" class="btn btn-warning" data-preview="#comment" value="<?php echo l('preview'); ?>" />
		</div>
	</form>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		traq.show_hide_custom_fields();
		$('#type').change(function() {
			traq.show_hide_custom_fields();
		});
	});
</script>
<?php } ?>
