<div class="new_ticket content">
	<h2 class="page-header"><?php echo l('new_ticket'); ?></h2>

	<form class="form-horizontal" role="form" action="<?php echo Request::requestUri(); ?>" method="post">
		<?php echo show_errors($ticket->errors); ?>
		<div class="tabular box">
			<div class="form-group">
				<label for="type" class="col-sm-2 control-label"><?php echo l('type'); ?></label>
				<div class="col-sm-10">				
					<?php echo Form::select('type', traq\models\Type::select_options(), array('value' => $ticket->type_id, 'class' => 'form-control')); ?>
				</div>
			</div>
			<div class="form-group">
				<label for="summary" class="col-sm-2 control-label"><?php echo l('summary'); ?></label>
				<div class="col-sm-10">		
					<?php echo Form::text('summary', array('value' => isset(Request::$post['summary']) ? Request::$post['summary'] : '', 'class' => 'form-control')); ?>
				</div>
			</div>
			<div class="form-group">
				<label for="description" class="col-sm-2 control-label"><?php echo l('description'); ?></label>
				<div class="col-sm-10">		
					<?php echo Form::textarea('description', array('class' => 'form-control editor', 'value' => $ticket->body, 'rows' => '6')); ?>
				</div>
			</div>
			<div class="form-group">
				<label for="milestone" class="col-sm-2 control-label"><?php echo l('milestone'); ?></label>
				<div class="col-sm-10">	
					<?php echo Form::select('milestone', $project->milestone_select_options('open'), array('value' => $ticket->milestone_id, 'class' => 'form-control')); ?>
					<abbr title="<?php echo l('help.milestone'); ?>" class="hint">?</abbr>
				</div>
			</div>
			
				<?php if (current_user()->permission($project->id, 'ticket_properties_set_version')) { ?>
			<div class="form-group">
				<label for="version" class="col-sm-2 control-label"><?php echo l('version'); ?></label>
				<div class="col-sm-10">	
					<?php echo Form::select('version', array_merge(array(array('value' => 0, 'label' => l('none'))), $project->milestone_select_options('all', 'DESC')), array('value' => $ticket->version_id, 'class' => 'form-control')); ?>
					<abbr title="<?php echo l('help.version'); ?>" class="hint">?</abbr>
				</div>
			</div>
				<?php } ?>
				<?php if (current_user()->permission($project->id, 'ticket_properties_set_component')) { ?>
			<div class="form-group">
				<label for="component" class="col-sm-2 control-label"><?php echo l('component'); ?></label>
				<div class="col-sm-10">	
					<?php echo Form::select('component', array_merge(array(array('value' => 0, 'label' => l('none'))), traq\models\Component::select_options($project->id)), array('value' => $ticket->component_id, 'class' => 'form-control')); ?>
					<abbr title="<?php echo l('help.component'); ?>" class="hint">?</abbr>
				</div>
			</div>
				<?php } ?>
				<?php if (current_user()->permission($project->id, 'ticket_properties_set_severity')) { ?>
			<div class="form-group">
				<label for="severity" class="col-sm-2 control-label"><?php echo l('severity'); ?></label>
				<div class="col-sm-10">	
					<?php echo Form::select('severity', traq\models\Severity::select_options(), array('value' => $ticket->severity_id, 'class' => 'form-control')); ?>
					<abbr title="<?php echo l('help.severity'); ?>" class="hint">?</abbr>
				</div>
			</div>
				<?php } ?>
				<?php if (current_user()->permission($project->id, 'ticket_properties_set_priority')) { ?>
			<div class="form-group">
				<label for="priority" class="col-sm-2 control-label"><?php echo l('priority'); ?></label>
				<div class="col-sm-10">	
					<?php echo Form::select('priority', traq\models\Priority::select_options(), array('value' => $ticket->priority_id, 'class' => 'form-control')); ?>
				</div>
			</div>
				<?php } ?>
				<?php if (current_user()->permission($project->id, 'ticket_properties_set_status')) { ?>
			<div class="form-group">
				<label for="status" class="col-sm-2 control-label"><?php echo l('status'); ?></label>
				<div class="col-sm-10">	
					<?php echo Form::select('status', traq\models\Status::select_options(), array('value' => $ticket->status_id, 'class' => 'form-control')); ?>
				</div>
			</div>
				<?php } ?>
				<?php if (current_user()->permission($project->id, 'ticket_properties_set_assigned_to')) { ?>
			<div class="form-group">
				<label for="assigned_to" class="col-sm-2 control-label"><?php echo l('assigned_to'); ?></label>
				<div class="col-sm-10">	
					<?php echo Form::select('assigned_to', array_merge(array(array('value' => 0, 'label' => l('none'))), $project->assignable_member_select_options()), array('value' => $ticket->assigned_to_id, 'class' => 'form-control')); ?>
				</div>
			</div>
				<?php } ?>
				<?php if (current_user()->permission($project->id, 'ticket_properties_set_tasks')) { ?>
			<div class="form-group">
				<label for="tasks" class="col-sm-2 control-label"><?php echo l('tasks'); ?></label>
				<div class="col-sm-10">	
					<button type="button" class="btn btn-primary" id="manage_ticket_tasks" data-url="<?php echo Request::base($project->href('tickets/0/tasks/manage'))?>"><?php echo l('manage')?></button>
					<div id="ticket_tasks_data">
						<input type="hidden" name="task_count" value="0">
						<input type="hidden" name="tasks">
					</div>
				</div>
			</div>
				<?php } ?>
				<?php if ($current_user->permission($project->id, 'ticket_properties_set_related_tickets')) { ?>
			<div class="form-group">
				<label for="related_tickets" class="col-sm-2 control-label"><?php echo l('related_tickets'); ?></label>
				<div class="col-sm-10">	
					<?php echo Form::text('related_tickets',array('class' => 'form-control')); ?>
				</div>
			</div>
				<?php } ?>
				<?php echo View::render('tickets/_custom_fields_form'); ?>
				<div class="clearfix"></div>
			</div>
		</div>
		<div class="actions btn-group">
			<input type="submit" class="btn btn-success" value="<?php echo l('create'); ?>" />
			<input type="button" class="btn btn-warning" data-preview="#description" value="<?php echo l('preview'); ?>" />
		</div>
	</form>
	<script type="text/javascript">
		$(document).ready(function(){
			if ($('#description').val() == '') {
				traq.load_ticket_template();
			}
			$('#type').change(function() {
				traq.load_ticket_template();
			});
		});
	</script>
</div>
