<div id="ticket_info">
	<h2 class="page-header"><?php echo htmlspecialchars($ticket->summary); ?>	
	<div class="ticket_actions pull-right">
		<div class="btn btn-default"><?php echo subscription_link_for($ticket); ?></div>
		<?php if ($current_user->permission($ticket->project_id, 'delete_tickets')) {
			echo HTML::link(l('delete'), $ticket->href('/delete'), array('class' => 'btn btn-danger', 'data-confirm' => l('confirm.delete_x', $ticket->summary)));
		} ?>
		<?php if ($current_user->permission($ticket->project_id, 'move_tickets')) {
			echo HTML::link(l('move'), $ticket->href('move'), array('class' => 'btn btn-warning'));
		} ?>
	</div>
</h2>	

	<div class="row well">
		<div class="col-md-12">	
			<div class="col-md-1">	
				<?php echo Form::label(l('ticket_id')); ?>
			</div>
			<div class="col-md-2">	
				<span class="value"><?php echo $ticket->ticket_id; ?></span>
			</div>
			<div class="col-md-1">	
				<?php echo Form::label(l('type')); ?>
			</div>
			<div class="col-md-2">			
				<span class="value"><?php echo $ticket->type->name; ?></span>
			</div>
			<div class="col-md-1">	
				<?php echo Form::label(l('owner')); ?>
			</div>
			<div class="col-md-2">
				<span class="value"><?php echo HTML::link(strshorten($ticket->user->name, 20), $ticket->user->href()); ?></span>
			</div>
			<div class="col-md-1">
				<?php echo Form::label(l('assigned_to')); ?>
			</div>
			<div class="col-md-2">	
				<span class="value"><?php echo $ticket->assigned_to ? HTML::link(strshorten($ticket->assigned_to->name, 20), $ticket->assigned_to->href()) : '-'; ?></span>
			</div>
		</div>
		<div class="col-md-12">			
			<div class="col-md-1">
				<?php echo Form::label(l('milestone')); ?>
			</div>
			<div class="col-md-2">				
				<span class="value"><?php echo $ticket->milestone ? HTML::link($ticket->milestone->name, $ticket->milestone->href()) : '-'; ?></span>
			</div>
			<div class="col-md-1">
				<?php echo Form::label(l('version')); ?>
			</div>
			<div class="col-md-2">	
				<span class="value"><?php echo $ticket->version ? $ticket->version->name : '-'; ?></span>
			</div>
			<div class="col-md-1">
				<?php echo Form::label(l('component')); ?>
			</div>
			<div class="col-md-2">			
				<span class="value"><?php echo $ticket->component ? $ticket->component->name : '-'; ?></span>
			</div>
			<div class="col-md-1">
				<?php echo Form::label(l('status')); ?>
			</div>		
			<div class="col-md-2">				
				<span class="value"><?php echo $ticket->status->name; ?></span>
			</div>
		</div>	
		<div class="col-md-12">	
			<div class="col-md-1">
				<?php echo Form::label(l('priority')); ?>
			</div>		
			<div class="col-md-2">			
				<span class="value"><?php echo $ticket->priority->name; ?></span>
			</div>
			<div class="col-md-1">
				<?php echo Form::label(l('severity')); ?>
			</div>		
			<div class="col-md-2">				
				<span class="value"><?php echo $ticket->severity->name; ?></span>
			</div>
			<div class="col-md-1">
				<?php echo Form::label(l('reported')); ?>
			</div>		
			<div class="col-md-2">				
				<span class="value"><?php echo time_ago($ticket->created_at, false, true); ?></span>
			</div>
			<div class="col-md-1">
				<?php echo Form::label(l('updated')); ?>
			</div>		
			<div class="col-md-2">				
				<span class="value" id="updated_at"><?php echo $ticket->updated_at > $ticket->created_at ? time_ago($ticket->updated_at, false, true) : l('never'); ?></span>
			</div>
		</div>
		<div class="col-md-12">	
			<div class="col-md-1">
				<?php echo Form::label(l('votes')); ?>
			</div>	
			<div class="col-md-2">
				<span class="value">
					<?php echo ($ticket->votes == 0) ? "<span id=\"votes\">{$ticket->votes}</span>" : HTML::link($ticket->votes, $ticket->href('#'), array('id' => 'votes', 'data-popover-hover' => Request::base($ticket->href('/voters')))); ?>
					<?php if (LOGGEDIN and $current_user->permission($project->id, 'vote_on_tickets') and !in_array($current_user->id, $ticket->extra['voted']) and $current_user->id != $ticket->user_id) {
						echo HTML::link('+', $ticket->href('/vote'), array('data-ajax' => true));
					} ?>
				</span>
			</div>	
			<div class="col-md-2">
				<?php echo Form::label(l('related_tickets')); ?>
				<ul class="value">
				<?php foreach ($ticket->related_tickets() as $related_ticket) { ?>
					<li><?php echo HTML::link("#" . $related_ticket->ticket_id, $related_ticket->href()); ?></li>
				<?php } ?>
				</ul>
			</div>
			<?php
			foreach ($custom_fields as $field) {
					if ($field_value = $ticket->custom_field_value($field->id)) {
			?>
			<div class="property">
				<?php echo Form::label($field->name); ?>
				<span class="value"><?php echo implode(', ', (array)$field_value->value); ?></span>
			</div>
			<?php }
			}
			?>
		
			<div class="clearfix"></div>
		</section>
		</div>

		
		<section id="description">
			<h3 class="section_title">
				<?php echo l('description'); ?>
				<?php if ($current_user->permission($project->id, 'edit_ticket_description')) {
					echo HTML::link('', $ticket->href() . '/edit', array('title' => l('edit_ticket'), 'data-overlay' => true, 'class' => 'button_edit'));
				} ?>
			</h3>
			<div class="body">
				<?php echo format_text($ticket->body, true); ?>
			</div>
		</section>
	</div>
	

	<?php if (is_array($ticket->tasks) and count($ticket->tasks)) { ?>
	<section id="tasks">
		<h3 class="section_title"><?php echo l('tasks')?></h3>
		<ul>
		<?php foreach ($ticket->tasks as $id => $task) { ?>
			<li class="task" id="task_<?php echo $id?>">
				<?php echo Form::checkbox("task[{$id}]", 1, array('data-task-id' => $id, 'data-url' => Request::base($ticket->href("tasks/{$id}")), 'checked' => $task['completed'], 'disabled' => !current_user()->permission($project->id, 'ticket_properties_complete_tasks')))?>
				<?php echo ticket_links($task['task'])?>
			</li>
		<?php } ?>
		</ul>
	</section>
	<?php } ?>


	
	<?php if ($current_user->permission($ticket->project_id, 'view_attachments') and $attachments = $ticket->attachments->exec() and $attachments->row_count() > 0) { ?>
	<section id="attachments">
		<h3 class="section_title"><?php echo l('attachments'); ?></h3>
		<ul>
		<?php foreach ($attachments->fetch_all() as $attachment) { ?>
			<li>
				<?php echo l('x_uploaded_by_x_x_ago', HTML::link("<span class=\"attachment_filename\">{$attachment->name}</span>", $attachment->href()), HTML::link(strshorten($attachment->user->name, 20), $attachment->user->href()), time_ago($attachment->created_at, false)); ?>
				<?php if ($current_user->permission($ticket->project_id, 'delete_attachments')) {
					echo HTML::link('', $attachment->href('/delete'), array('class' => 'button_delete', 'data-confirm' => l('confirm.delete_x', $attachment->name)));
				} ?>
			</li>
		<?php } ?>
		</ul>
	</section>
	<?php } ?>

	<?php echo View::render('tickets/_ticket_history'); ?>

	<?php echo View::render('tickets/_update_ticket_form'); ?>
</div>
