<div class="row">
<div class="col-md-1"></div>
<div class="col-md-10">
<div class="panel panel-default">
	<div class="panel-heading">
		<strong><?php echo l('register'); ?></strong>
	</div>
	<div class="panel-body">
<?php if (!$validation_required) { ?>
		<?php if (isset($user)) { echo show_errors($user->errors); } ?>
		<form class="form-horizontal" role="form" action="<?php echo Request::base('register'); ?>" method="post">
			<div class="form-group">
				<label for="username" class="col-sm-2 control-label"><?php echo l('username'); ?></label>
				<div class="col-sm-10">	
					<?php echo Form::text('username', array('class' => "form-control", 'id' => "username")); ?>
				</div>	
			</div>
			<div class="form-group">
				<label for="name" class="col-sm-2 control-label"><?php echo l('name'); ?></label>
				<div class="col-sm-10">	
					<?php echo Form::text('name', array('class' => "form-control", 'id' => "name", 'required' => "required")); ?>
				</div>	
			</div>
			<div class="form-group">
				<label for="password" class="col-sm-2 control-label"><?php echo l('password'); ?></label>
				<div class="col-sm-10">	
					<?php echo Form::password('password', array('class' => "form-control", 'id' => "password", 'required' => "required")); ?>
				</div>	
			</div>
			<div class="form-group">
				<label for="email" class="col-sm-2 control-label"><?php echo l('email'); ?></label>
				<div class="col-sm-10">	
					<?php echo Form::text('email', array('class' => "form-control", 'id' => "email", 'required' => "required")); ?>
				</div>	
			</div>
			<?php FishHook::run('template:users/register'); ?>
			<center><div class="btn-group">
				<input type="submit" class="btn btn-primary" value="<?php echo l('register'); ?>" />
				<?php echo HTML::link(l('cancel'), '/login', array('class' => 'btn btn-danger')); ?>
			</div></center>
		</form>
<?php } else { ?>
		<?php echo l('please_validate_your_account')?>
<?php } ?>
	</div>
</div>
</div>
<div class="col-md-1"></div>
</div>