<div class="row">
<div class="col-md-1"></div>
<div class="col-md-10">
<div class="panel panel-default">
	<div class="panel-heading">
		<strong><?php echo l('forgot_password'); ?></strong>
	</div>
	<div class="panel-body">
<?php if (isset($password_reset) and $password_reset = true) { ?>
		<div class="box">
			<?php echo l('password_reset.success', $new_password); ?>
		</div>
<?php } elseif (isset($reset_email_sent) and $reset_email_sent == true) { ?>
		<div class="box">
			<?php echo l('password_reset.email_sent'); ?>
		</div>
<?php } else { ?>
		<?php if (isset($error) and $error) { ?>
		<div class="error">
			<?php echo l('errors.invalid_username'); ?>
		</div>
<?php } ?>
		<form class="form-horizontal" role="form" action="<?php echo Request::base('login/resetpassword'); ?>" method="post">
			<div class="form-group">
				<label for="username" class="col-sm-2 control-label"><?php echo l('username'); ?></label>
				<div class="col-sm-10">	
					<?php echo Form::text('username', array('class' => "form-control", 'id' => "username", 'required' => "required")); ?>
				</div>	
			</div>
			<center><div class="btn-group">
				<input type="submit" class="btn btn-primary" value="<?php echo l('reset'); ?>" />
				<?php echo HTML::link(l('cancel'), '/login', array('class' => 'btn btn-danger')); ?>
			</div></center>
		</form>
<?php } ?>
	</div>
</div>
</div>
<div class="col-md-1"></div>
</div>