<div class="profile content">
	<h2 id="page_title"><?php echo l('xs_profile', $profile->name); ?></h2>

	<div class="row">
	<div class="col-md-5">
		<div class="panel panel-default">		
			<div class="panel-heading">
				<strong class="panel-title"><?php echo l('information'); ?></strong>
			</div>
		
			<ul class="list-group">
				<li class="list-group-item"><?php echo l('member_since'); ?>
				<span class="pull-right"><?php echo ($profile->created_at ? ldate(settings('date_format')) : l('unknown')); ?></li>
				
				<li class="list-group-item"><?php echo l('group'); ?>
				<span class="pull-right"><?php echo $profile->group->name; ?></li>
				
				<li class="list-group-item"><?php echo l('assigned_tickets'); ?>
				<span class="badge"><?php echo $profile->assigned_tickets->exec()->row_count(); ?></li>

				<li class="list-group-item"><?php echo l('tickets_created'); ?>
				<span class="badge"><?php echo $profile->tickets->exec()->row_count(); ?></li>

				<li class="list-group-item"><?php echo l('ticket_updates'); ?>
				<span class="badge"><?php echo $profile->ticket_updates->exec()->row_count(); ?></li>

				<?php FishHook::run('template:users/users/view', array($profile)); ?>
			</ul>

			<div class="clearfix"></div>
		</div>
		</div> <!-- END Collum md 6 -->

		<div class="col-md-2"></div> <!-- Fixing Position -->
		
		<div class="col-md-5">
			<?php if (count($profile->projects())) { ?>
			<div class="panel panel-default">		
				<div class="panel-heading">
					<strong class="panel-title"><?php echo l('projects'); ?></strong>
				</div>
				
				<?php foreach ($profile->projects() as $project) {
					if (!$current_user->permission($project[0]->id, 'view')) { continue; }
					?>
					<ul class="list-group">
						<li class="list-group-item"><?php echo HTML::link($project[0]->name, $project[0]->href()); ?>
						<span class="pull-right"><?php echo $project[1]->name; ?></li>
					</ul>
				<?php } ?>
			</div>
			<?php } ?>
		</div>
	</div>

	<?php if (count($profile->projects())) { ?>
	<div class="panel panel-default">		
		<div class="panel-heading">
			<strong class="panel-title"><?php echo l('assigned_tickets'); ?></strong>
		</div>


		<table class="table table-hover">
			<thead>
				<th class="summary"><?php echo l('summary'); ?></th>
				<th class="project"><?php echo l('project'); ?></th>
				<th class="status"><?php echo l('status'); ?></th>
				<th class="created"><?php echo l('created'); ?></th>
				<th class="updated"><?php echo l('updated'); ?></th>
			</thead>
			<tbody>
			<?php foreach ($profile->assigned_tickets->order_by('is_closed', 'ASC')->exec()->fetch_all() as $ticket) {
				if (!$current_user->permission($ticket->project_id, 'view')) { continue; }
				?>
				<tr>
					<td><?php echo HTML::link($ticket->summary, $ticket->href()); ?></td>
					<td><?php echo HTML::link($ticket->project->name, $ticket->project->href()); ?></td>
					<td><?php echo $ticket->status->name; ?></td>
					<td><?php echo time_ago($ticket->created_at, 0); ?></td>
					<td><?php echo $ticket->updated_at > $ticket->created_at ? time_ago($ticket->updated_at, 0) : l('never'); ?></td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
	</div>
	<?php } ?>

	<div class="clearfix"></div>
</div>
