<div class="content">
	<div class="panel panel-success">
		<div class="panel-heading"><strong><?php echo l('enabled_plugins'); ?></strong></div>
		<div class="panel-body">
			<?php echo View::render('admin/plugins/_list', array('plugins' => $plugins['enabled'])); ?>
		</div>
	</div>
	<div class="panel panel-danger">
		<div class="panel-heading"><strong><?php echo l('disabled_plugins'); ?></strong></div>
		<div class="panel-body">
			<?php echo View::render('admin/plugins/_list', array('plugins' => $plugins['disabled'])); ?>
		</div>
	</div>

</div>
