<h2><?php echo l('settings'); ?></h2>
<form class="form-horizontal" action="<?php echo Request::requestUri(); ?>" method="post" role="form">
	<?php if (isset($errors)) { show_errors($errors); } ?>
	<div class="panel panel-default">
		<div class="panel-heading">
			<strong><?php echo l('traq'); ?></strong>
		</div>
		<div class="panel-body">	
			<div class="form-group">
				<label for="settings_title" class="col-sm-2 control-label"><?php echo l('traq_title'); ?></label>
				<div class="col-sm-10">
					<?php echo Form::text('settings[title]', array('value' => settings('title'), 'class' => "form-control", 'id' => "settings_title")); ?>
				</div>
			</div>
			
			<div class="form-group">
				<label for="settings_locale" class="col-sm-2 control-label"><?php echo l('default_language'); ?></label>
				<div class="col-sm-10">
					<?php echo Form::select('settings[locale]', locale_select_options(), array('value' => settings('locale'), 'class' => "form-control", 'id' => "settings_locale")); ?>
				</div>
			</div>
			
			<div class="form-group">
				<label for="settings_theme" class="col-sm-2 control-label"><?php echo l('theme'); ?></label>
				<div class="col-sm-10">
					<?php echo Form::select('settings[theme]', theme_select_options(), array('value' => settings('theme'), 'class' => "form-control", 'id' => "settings_theme")); ?>
				</div>
			</div>
		</div>
	</div>

	<div class="panel panel-default">
		<div class="panel-heading">
			<strong><?php echo l('settings.site.legend'); ?></strong>
		</div>
		<div class="panel-body">	
			<div class="form-group">
				<label for="settings_sitename" class="col-sm-2 control-label"><?php echo l('settings.site.name'); ?></label>
				<div class="col-sm-10">	
					<?php echo Form::text('settings[site_name]', array('value' => settings('site_name'), 'class' => "form-control", 'id' => "settings_sitename")); ?>
				</div>
			</div>
			<div class="form-group">
				<label for="settings_sitename" class="col-sm-2 control-label"><?php echo l('settings.site.url'); ?></label>
				<div class="col-sm-10">	
					<?php echo Form::text('settings[site_url]', array('value' => settings('site_url'), 'class' => "form-control", 'id' => "settings_siteurl")); ?>
				</div>
			</div>
		</div>
	</div>

	<fieldset class="tabular section box">
		<legend><?php echo l('users'); ?></legend>
		<div class="group">
			<label><?php echo l('allow_registration'); ?></label>
			<?php echo Form::select('settings[allow_registration]',
				array(array('label' => l('yes'), 'value' => 1), array('label' => l('no'), 'value' => 0)),
				array('value' => settings('allow_registration'))
				);
			?>
		</div>
		<div class="group">
			<label><?php echo l('email_validation'); ?></label>
			<?php echo Form::select('settings[email_validation]',
				array(array('label' => l('yes'), 'value' => 1), array('label' => l('no'), 'value' => 0)),
				array('value' => settings('email_validation'))
				);
			?>
		</div>
	</fieldset>

	<fieldset class="tabular section box">
		<legend><?php echo l('date_and_time'); ?></legend>
		<div class="group">
			<label><?php echo l('date_time_format'); ?></label>
			<?php echo Form::text('settings[date_time_format]', array('value' => settings('date_time_format'))); ?>
		</div>
		<div class="group">
			<label><?php echo l('date_format'); ?></label>
			<?php echo Form::text('settings[date_format]', array('value' => settings('date_format'))); ?>
		</div>
		<div class="group">
			<label><?php echo l('timeline_day_format'); ?></label>
			<?php echo Form::text('settings[timeline_day_format]', array('value' => settings('timeline_day_format'))); ?>
		</div>
		<div class="group">
			<label><?php echo l('timeline_time_format'); ?></label>
			<?php echo Form::text('settings[timeline_time_format]', array('value' => settings('timeline_time_format'))); ?>
		</div>
	</fieldset>

	<fieldset class="tabular section box">
		<legend><?php echo l('notifications'); ?></legend>
		<div class="group">
			<label><?php echo l('notifications_from_email'); ?></label>
			<?php echo Form::text('settings[notification_from_email]', array('value' => settings('notification_from_email'))); ?>
		</div>
	</fieldset>

	<fieldset class="tabular section box">
		<legend><?php echo l('tickets'); ?></legend>
		<div class="group">
			<label><?php echo l('ticket_history_sorting'); ?></label>
			<?php echo Form::select('settings[ticket_history_sorting]', ticket_history_sorting_options(), array('value' => settings('ticket_history_sorting'))); ?>
		</div>
		<div class="group">
			<label><?php echo l('ticket_creation_delay'); ?></label>
			<?php echo Form::text('settings[ticket_creation_delay]', array('value' => settings('ticket_creation_delay'))); ?> <abbr title="<?php echo l('help.ticket_creation_delay'); ?>">?</abbr>
		</div>
	</fieldset>

	<div class="actions">
		<input type="submit" value="<?php echo l('save'); ?>" />
	</div>
</form>