<div class="content">
	<?php echo HTML::link(l('new_user'), '/admin/users/new', array('class' => 'btn btn-primary')) ; ?>
	<table class="table table-hover">
		<thead>
			<th><?php echo l('username'); ?></th>
			<th><?php echo l('name'); ?></th>			
			<th><?php echo l('group'); ?></th>
			<th><!--?php echo l('actions'); ?--></th>
		</thead>
		<tbody>
		<?php foreach ($users as $user) { ?>
			<tr>
				<td><?php echo HTML::link($user->username, "/admin/users/{$user->id}/edit"); ?></td>
				<td><?php echo $user->name; ?></td>
				<td><?php echo $user->group->name; ?></td>
				<td align="right">
					<?php echo HTML::link(l('edit'), "/admin/users/{$user->id}/edit", array('class' => 'label label-warning')); ?>
					<?php echo HTML::link(l('delete'), "/admin/users/{$user->id}/delete", array('class' => 'label label-danger', 'data-confirm' => l('confirm.delete_x', $user->username))); ?>
				</td>
			</tr>
		<?php } ?>
		</tbody>
	</table>
</div>