<title><?php echo implode(' - ', array_reverse($traq->title)); ?></title>
		<meta charset="UTF-8" />
		<?php echo HTML::css_link('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'); ?>
		<?php echo HTML::css_link('//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css'); ?>
		<?php echo HTML::css_link('//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css'); ?>
		<!--[if lt IE 8]>
		<?php //echo HTML::css_link(Request::base() . 'css.php?css=ie'); ?>
		<![endif]-->
		<?php echo HTML::js_inc('//code.jquery.com/jquery-1.11.0.min.js'); ?>
		<?php echo HTML::js_inc('//code.jquery.com/ui/1.11.0/jquery-ui.js'); ?>
		<?php echo HTML::js_inc('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.js'); ?>
		<?php echo HTML::js_inc(Request::base() . 'js.php?js=all'); ?>
		<?php echo HTML::js_inc(Request::base('_js')); ?>
		<?php FishHook::run('template:layouts/global/head'); ?>
<?php foreach ($app->feeds as $feed) { ?><link type="application/atom+xml" rel ="alternate" href="<?php echo $feed[0]; ?>">
<?php } ?>
