<!DOCTYPE html>
<html>
	<head>
		<?php echo View::render('layouts/_head'); ?>
		<?php FishHook::run('template:layouts/admin/head'); ?>
	</head>
	<body>
		<div id="overlay_blackout"></div>
		<div id="overlay"></div>
		<div id="popover" class="popover"></div>
		<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
				
			<div class="container-fluid">
		
				<div class="navbar-header">

					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						
					</button>
					
					<a class="navbar-brand" href="/admin">AdminCP</a>
					<?php //echo View::render('layouts/_project_switcher'); ?>
					
				</div>
			
				<div class="collapse navbar-collapse">
				
					<ul class="nav navbar-nav">
						
						<li<?php echo iif(active_nav('/admin'), ' class="active"')?>><?php echo HTML::link(l('dashboard'), "/admin"); ?></li>
						<li<?php echo iif(active_nav('/admin/settings(.*)'), ' class="active"')?>><?php echo HTML::link(l('settings'), "/admin/settings"); ?></li>
						<li<?php echo iif(active_nav('/admin/projects(.*)'), ' class="active"')?>><?php echo HTML::link(l('projects'), "/admin/projects"); ?></li>
						<li<?php echo iif(active_nav('/admin/roles(.*)'), ' class="active"')?>><?php echo HTML::link(l('roles'), "/admin/roles"); ?></li>
						<li<?php echo iif(active_nav('/admin/users(.*)'), ' class="active"')?>><?php echo HTML::link(l('users'), "/admin/users"); ?></li>
						<li<?php echo iif(active_nav('/admin/groups(.*)'), ' class="active"')?>><?php echo HTML::link(l('groups'), "/admin/groups"); ?></li>
						<li<?php echo iif(active_nav('/admin/plugins(.*)'), ' class="active"')?>><?php echo HTML::link(l('plugins'), "/admin/plugins"); ?></li>
						<li<?php echo iif(active_nav('/admin/tickets/types(.*)'), ' class="active"')?>><?php echo HTML::link(l('types'), "/admin/tickets/types"); ?></li>
						<li<?php echo iif(active_nav('/admin/tickets/statuses(.*)'), ' class="active"')?>><?php echo HTML::link(l('statuses'), "/admin/tickets/statuses"); ?></li>
						<li<?php echo iif(active_nav('/admin/priorities(.*)'), ' class="active"')?>><?php echo HTML::link(l('priorities'), "/admin/priorities"); ?></li>
						<li<?php echo iif(active_nav('/admin/severities(.*)'), ' class="active"')?>><?php echo HTML::link(l('severities'), "/admin/severities"); ?></li>
						<?php FishHook::run('template:layouts/admin/main_nav'); ?>
					
					</ul>
					
					<ul class="nav navbar-nav navbar-right">
						
						<?php echo View::render('layouts/_meta_nav'); ?>
						
					</ul>
					
				</div> <!-- END Navbar Collapse -->
			
			</div> <!-- END Navbar Container -->
			
		</nav>
		
		<div class="container">
		<div class="row">
		<div class="col-md-1"></div>
		<div class="col-md-10">
<?php echo $content; ?>
		</div>
		<div class="col-md-1"></div>
		</div>
		</div>
		
		<footer>
				
				<div class="container-fluid">
						
							<?php echo l('copyright', TRAQ_VER, date("Y")); ?>
							<p class="footer-right">Bootstrap Theme by <a href="http://github.com/paulhobbel">Paul Hobbel</a></p>
				
				</div>
				
		</footer>
		<!-- <?php echo round((microtime(true) - START_TIME), 2); ?>s, <?php echo round((memory_get_peak_usage() - START_MEM) / pow(1024, 2), 3); ?>mb -->
	</body>

</html>
