<div class="content">
	<?php echo HTML::link(l('new_type'), '/admin/tickets/types/new', array('class' => 'btn btn-primary', 'data-overlay' => true)); ?>
	<table class="table table-hover">
		<thead>
			<th><?php echo l('name'); ?></th>	
			<th><?php echo l('bullet'); ?></th>				
			<th><?php echo l('changelog'); ?></th>				
			<th><!--?php echo l('actions'); ?--></th>
		</thead>
		<tbody>
		<?php foreach ($types as $type) { ?>
			<tr>
				<td><?php echo HTML::link($type->name, "/admin/tickets/types/{$type->id}/edit", array('data-overlay' => true)); ?></td>
				<td><?php echo $type->bullet ?></td>					
				<td><?php echo $type->changelog ? '&#10003;' : '&times;' ?></td>				
				<td align="right">
					<?php echo HTML::link(l('edit'), "/admin/tickets/types/{$type->id}/edit", array('class' => 'btn btn-xs btn-warning', 'data-overlay' => true)); ?>
					<?php echo HTML::link(l('delete'), "/admin/tickets/types/{$type->id}/delete", array('class' => 'btn btn-xs btn-danger', 'data-confirm' => l('confirm.delete_x', $type->name))); ?>
				</td>
			</tr>
		<?php } ?>
		</tbody>
	</table>
</div>