<div class="usercp password content">
	<h2 class="page-header"><?php echo l('usercp'); ?></h2>
</div>
<?php echo View::render('usercp/_nav'); ?>
<div class="usercp password content">
	<?php echo show_errors($user->errors); ?>
	<form class="form-horizontal" role="form" action="<?php echo Request::requestUri(); ?>" method="post">
		<fieldset class="box push-6 span-11">
			<legend><?php echo l('password'); ?></legend>

			<div class="tabular">
				<div class="form-group">
					<label for="old_password" class="col-sm-2 control-label"><?php echo l('old_password'); ?></label>
					<div class="col-sm-10">
						<?php echo Form::password('password', array('class' => 'form-control', 'id' => 'password')); ?>
					</div>
				</div>			
				<div class="form-group">
					<label for="new_password" class="col-sm-2 control-label"><?php echo l('new_password'); ?></label>
					<div class="col-sm-10">
						<?php echo Form::password('new_password', array('class' => 'form-control', 'id' => 'new_password')); ?>
					</div>
				</div>	
				<div class="form-group">
					<label for="new_password" class="col-sm-2 control-label"><?php echo l('confirm_password'); ?></label>
					<div class="col-sm-10">
						<?php echo Form::password('confirm_password', array('class' => 'form-control', 'id' => 'confirm_password')); ?>
					</div>
				</div>	
				<?php FishHook::run('template:users/usercp/password'); ?>
			</div>
		</fieldset>

		<div class="clearfix"></div>
		<div class="actions">
			<input type="submit" class="btn btn-primary" value="<?php echo l('save'); ?>" />
		</div>
	</form>
</div>
